Requirement already satisfied: pandas_datareader in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (0.10.0)
Requirement already satisfied: lxml in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from pandas_datareader) (6.0.0)
Requirement already satisfied: pandas>=0.23 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from pandas_datareader) (2.3.1)
Requirement already satisfied: requests>=2.19.0 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from pandas_datareader) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.23->pandas_datareader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from pandas>=0.23->pandas_datareader) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas_datareader) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.19.0->pandas_datareader) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zaidi house\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.19.0->pandas_datareader) (2025.6.15)
